paritytech/txwrapper-core

CHAIN_BUILDER.md
package.json
packages/txwrapper-acala/package.json
packages/txwrapper-acala/src/index.ts
packages/txwrapper-core/package.json
packages/txwrapper-core/src/core/index.ts
packages/txwrapper-core/src/types/index.ts
packages/txwrapper-core/src/types/registry.ts
packages/txwrapper-examples/package.json
packages/txwrapper-examples/src/mandala.ts
packages/txwrapper-orml/package.json
packages/txwrapper-orml/src/test-helpers/getRegistryMandala.ts
packages/txwrapper-polkadot/package.json
packages/txwrapper-polkadot/src/index.ts
packages/txwrapper-registry/package.json
packages/txwrapper-registry/src/index.ts
yarn.lock

Closes #47, Closes #46, Closes #45
- Transition packages to use their own `getRegistry` function in order to decrease deps and supply chain waits for types.
- Add a chain builder example for how to create local `getRegistry`.
- Remove apps-config dep for txwrapper-orml to reduce package size; replaced with acala types as a dev dep. I chose to use the acala types over orml because it is helpful for the `decode` function tests to be associated with the specific runtime of a chain.

feat: Use local `getRegistry` functions

---

packages/txwrapper-substrate/src/methods/index.ts
packages/txwrapper-substrate/src/methods/vesting/index.ts
packages/txwrapper-substrate/src/methods/vesting/vest.spec.ts
packages/txwrapper-substrate/src/methods/vesting/vest.ts
packages/txwrapper-substrate/src/methods/vesting/vestOther.spec.ts
packages/txwrapper-substrate/src/methods/vesting/vestOther.ts
packages/txwrapper-substrate/src/test-helpers/TEST_METHOD_ARGS.ts

Migrate over the vesting methods (excluding deprecated ones) from txwrapper to txwrapper-core/txwrapper-substrate.
`./packages/txwrapper-substrate/src/test-helpers/TEST_METHOD_ARGS.ts`
Add the vesting key for testing.
`./packages/txwrapper-substrate/src/methods/vesting`
Add  `vest` and `vestOther` along with their tests.

feat: add vesting methods to txwrapper-substrate

---

packages/txwrapper-substrate/src/methods/democracy/index.ts
packages/txwrapper-substrate/src/methods/democracy/types.ts
packages/txwrapper-substrate/src/methods/democracy/vote.spec.ts
packages/txwrapper-substrate/src/methods/democracy/vote.ts
packages/txwrapper-substrate/src/methods/index.ts
packages/txwrapper-substrate/src/test-helpers/TEST_METHOD_ARGS.ts

Migrate over the un-deprecated democracy methods from txwrapper to txwrapper-core/txwrapper-substrate.
`./packages/txwrapper-substrate/src/test-helpers/TEST_METHOD_ARGS.ts`
Add the democracy key for testing. 
`./packages/txwrapper-substrate/src/methods/democracy`
Add `vote` method and its tests, as well as corresponding types.

feat: add democracy methods to txwrapper-substrate

---

README.md
package.json

The publish script did not generate change logs as expected. So instead of relying on `lerna publish` to call `lerna version`, this calls `lerna version` upfront prior to publishing.

build(deploy): Improve deploy script

---

.eslintrc.js
.gitignore
.prettierrc.js
babel.config.js
jest.config.js
package.json
packages/txwrapper-acala/package.json
packages/txwrapper-core/package.json
packages/txwrapper-core/src/core/construct/createSignedTx.spec.ts
packages/txwrapper-core/src/core/decode/decode.spec.ts
packages/txwrapper-core/src/core/decode/decodeUnsignedTx.ts
packages/txwrapper-core/src/core/decode/test-helpers/itDecodesBalancesTransferCommon.ts
packages/txwrapper-core/src/core/method/defineMethod.ts
packages/txwrapper-core/src/core/method/toTxMethod.ts
packages/txwrapper-core/src/core/util/importPrivateKey.spec.ts
packages/txwrapper-examples/package.json
packages/txwrapper-examples/src/mandala.ts
packages/txwrapper-examples/src/polkadot.ts
packages/txwrapper-examples/src/util.ts
packages/txwrapper-orml/package.json
packages/txwrapper-orml/src/test-helpers/getRegistryMandala.ts
packages/txwrapper-polkadot/package.json
packages/txwrapper-registry/package.json
packages/txwrapper-substrate/package.json
packages/txwrapper-template/examples/util.ts
packages/txwrapper-template/package.json
packages/txwrapper-template/tsconfig.json
tsconfig.build.json
yarn.lock

Emitted .js is now es2019, requiring node >= 12.
- Use @substrate/dev for build configuration
- new tsconfig.json targets es2019
- prettier now uses a 2 space hard tab instead of a 4 space hard tab
- Babel is now used to transpile the @polkadot/* packages `.js` from ESM to CJS for jest
- bump deps

fix(types)!: polkadot/api to v4 w. esm; Use substrate/dev for build

---

package.json
packages/txwrapper-acala/package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
packages/txwrapper-orml/package.json
packages/txwrapper-registry/package.json
yarn.lock

@acala-network/type-definitions
* @substrate/txwrapper-orml: 0.6.2-22 → 0.7.1
* txwrapper-acala: 0.6.2-22 → 0.7.1
@polkadot/api
* @substrate/txwrapper-core: 4.0.3 → 4.1.1
* @substrate/txwrapper-examples: 4.0.3 → 4.1.1
@polkadot/apps-config
* @substrate/txwrapper-registry: 0.83.1 → 0.84.1
@polkadot/networks
* @substrate/txwrapper-registry: 6.0.5

fix(types): Bump deps to get latest types

---

packages/txwrapper-core/src/core/construct/createSigningPayload.ts
packages/txwrapper-examples/package.json
packages/txwrapper-examples/src/polkadotBatchAll.ts
packages/txwrapper-substrate/src/methods/utility/batchAll.spec.ts
packages/txwrapper-substrate/src/methods/utility/batchAll.ts
packages/txwrapper-substrate/src/methods/utility/index.ts

Adds the pallet method `utility.batchAll` to the txwrapper-substrate package. Additionally it adds an example for how to use the new method in txwrapper-examples; there has been questions in the past about how to create a batch with other txwrapper calls.
- Update incorrect docs in `createSigningPayload` that did not account for how to signining payloads over 256 bits need to be hashed. (I consider this a bug because people base there signing code off these docs.) 
relates to: https://github.com/paritytech/txwrapper/pull/410
- Change the `transfer` example to use `transferKeepAlive` to reflect best practices for reducing replay attacks.
- It may make sense to make a PR to polkadot-js's `ExtrinsicPayload` to add a `.toEncodedSigningPayload` that produces an encoded u8a/hex string ready to …

feat(substrate): Add pallet method `utility.batchAll` + example

---

packages/txwrapper-acala/package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
packages/txwrapper-orml/package.json
packages/txwrapper-registry/package.json
yarn.lock

@acala-network/type-definitions
* @substrate/txwrapper-orml: 0.7.1 → 0.7.2-1
* txwrapper-acala: 0.7.1 → 0.7.2-1
@polkadot/api
* @substrate/txwrapper-core: 4.1.1 → 4.2.1
* @substrate/txwrapper-examples: 4.1.1 → 4.2.1
@polkadot/apps-config
* @substrate/txwrapper-registry: 0.84.1 → 0.85.1
@polkadot/networks
* @substrate/txwrapper-registry: 6.0.5

fix(deps): Update `polkadot.js` scoped deps to get latest substrate and chain specific types

---

package.json
packages/txwrapper-acala/package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
packages/txwrapper-orml/package.json
packages/txwrapper-registry/package.json
yarn.lock

@acala-network/type-definitions
* @substrate/txwrapper-orml: 0.7.2-1 → 0.7.2-4
* txwrapper-acala: 0.7.2-1 → 0.7.2-4
@polkadot/api
* @substrate/txwrapper-core: 4.2.1 → 4.3.1
* @substrate/txwrapper-examples: 4.2.1 → 4.3.1
@polkadot/apps-config
* @substrate/txwrapper-registry: 0.85.1 → 0.86.2
@polkadot/networks
* @substrate/txwrapper-registry: 6.0.5

fix(types): Update deps to get latest polkadot-js types

---

package.json
packages/txwrapper-acala/package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
packages/txwrapper-orml/package.json
packages/txwrapper-polkadot/package.json
packages/txwrapper-registry/package.json
packages/txwrapper-substrate/package.json
packages/txwrapper-template/package.json

This PR aims to handle a behavior that yarn 2.x introduces. Being in a workspace we now need to share scripts accessing `bin` commands from `@substrate/dev`. This is only useful if you are developing in a single package and want to run the build locally. 
For example, if we call `yarn build` from the root directory it has access to the `bin` commands, and will then be accessible to the script calls in each packages `package.json`.  If we were to `cd` into one of the packages they no longer have access, therefore we need to share scripts from the root directory. That can be achieved by adding a colon `:` in the root package.json directory followed by a  `cd $INIT_CWD &&` in the scripts itself.
For example: `"build:workspace": "cd $INIT_CWD && rimraf lib/ && substrate-exec-tsc -p …

fix: workspace script sharing

---

packages/txwrapper-core/package.json
packages/txwrapper-core/src/core/metadata/createDecorated.ts
packages/txwrapper-examples/package.json
packages/txwrapper-registry/package.json
yarn.lock

- Bump polkadot-js scoped deps
- update `decorateConstants` usage to account for new version parameter
sister PR to https://github.com/paritytech/txwrapper/pull/433

fix: update polkadot-js deps; update `decorateConstants` usage

---

README.md
packages/txwrapper-core/package.json
packages/txwrapper-core/src/core/decode/decodeSigningPayload.ts
packages/txwrapper-examples/package.json
packages/txwrapper-registry/package.json
yarn.lock

changes:
- Update polkadot-js/api
- Remove the error log message suppression in decodeSigningPayloads createTypeUnsafe because it is no longer option (and it no longer logs the error).
rel: polkadot-js/api#3480, paritytech/txwrapper/pull/438

fix: Bump polkadot-js/api; Remove deprecated createType log option

---

README.md

Just a little more in the "notes" section on undoing things you may run into, and a note to remember to log in to NPM (because I forgot!)

docs: update release and publishing docs

---

README.md

Just wanted to tweak the release guide a wee bit to cover the issue that I hit publishing 1.2.4

Make sure that things are built if skipping to the publish step

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-core/src/core/construct/createSignedTx.ts
packages/txwrapper-core/src/test-helpers/signWithAlice.ts
packages/txwrapper-examples/package.json
packages/txwrapper-examples/src/util.ts
packages/txwrapper-registry/package.json
packages/txwrapper-template/examples/util.ts
yarn.lock

This bumps the following deps
"@polkadot/api": "6.7.1",
"@polkadot/networks": "7.8.2",
"@polkadot/apps-config": "0.98.2-57",
-dev
"@polkadot/util-crypto": "^7.8.2"

fix: bump deps

---

package.json

This adds a lerna lifecycle script that will fix our failing CI tests for releases. 
TL:DR -  The lerna workflow we currently have is updating the versioning for all the packages but not updating the `yarn.lock`. This script fixes that. 
closes: [#125](https://github.com/paritytech/txwrapper-core/issues/125)

fix: add lifecycle script to fix CI error on release

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-core/src/core/decode/decodeSignedTx.ts
packages/txwrapper-core/src/core/method/toTxMethod.ts
packages/txwrapper-core/src/index.ts
packages/txwrapper-examples/package.json
packages/txwrapper-registry/package.json
yarn.lock

~~Currently, this breaks all our of registry.createType instances. Working on a fix.~~ <- This was a local issue. 
Updates the following polkadot-js deps. 
"@polkadot/api" -> 7.0.2
"@polkadot/networks" -> 8.2.2
"@polkadot/apps" -> 0.99.1
- Add `import '@polkadot/api-augment';` as required by polkadot-js v7.0.1
- Update types import path for `AbstractInt` to use `types-codec`

fix(types): bump polkadot-js deps

---

packages/txwrapper-substrate/src/methods/proxy/index.ts
packages/txwrapper-substrate/src/methods/proxy/killAnonymous.spec.ts
packages/txwrapper-substrate/src/methods/proxy/killAnonymous.ts
packages/txwrapper-substrate/src/test-helpers/TEST_METHOD_ARGS.ts

closes: [#163](https://github.com/paritytech/txwrapper-core/issues/163)
ref: 
[paritytech/substrate proxy::kill_anonymous](https://github.com/paritytech/substrate/blob/master/frame/proxy/src/lib.rs#L361)
[polkadot-js/api proxy::killAnonymous](https://github.com/polkadot-js/api/blob/53eecf622029f5ba19938f340e06e7226c9ae941/packages/api-augment/src/polkadot/tx.ts#L2185)

feat: add proxy::killAnonymous method

---

packages/txwrapper-core/.npmignore
packages/txwrapper-core/package.json
packages/txwrapper-polkadot/.npmignore
packages/txwrapper-polkadot/package.json
packages/txwrapper-registry/.npmignore
packages/txwrapper-registry/package.json
packages/txwrapper-substrate/.npmignore
packages/txwrapper-substrate/package.json
tsconfig.json

This redirects the build source to reference `.npmignore` instead of the `package.json` -> `files`. I haven't done the exact size comparison, but were looking at a decrease in size by probably 60-70%.
All the tests will now be removed, as well as test-helpers.

fix: decrease npm build, bundle size

---

packages/txwrapper-core/src/core/construct/createSignedTx.ts
packages/txwrapper-core/src/core/metadata/getRegistryBase.ts
packages/txwrapper-core/src/core/method/defineMethod.ts
packages/txwrapper-core/src/types/method.ts
packages/txwrapper-core/src/types/registry.ts
packages/txwrapper-polkadot/src/index.ts

This PR gives support for signed, and user extensions. 
`createSignedTx` -> its `options` param now takes in an optional `signedExtensions`, and `userExtensions` field
`getRegistryBase` -> its only param now takes in an optional `signedExtensions`, and `userExtensions` field
`defineMethod` -> its `options` param now takes in an optional `signedExtensions`, and `userExtensions` field
`getRegistry` -> its only param now takes in an optional `signedExtensions`, and `userExtensions` field, as well as `asCallsOnlyArg`
closes: [#106](https://github.com/paritytech/txwrapper-core/issues/106) [#168](https://github.com/paritytech/txwrapper-core/issues/168)

feat: support for signedExtentions, and userExtensions

---

README.md
packages/txwrapper-orml/src/test-helpers/constants.ts
packages/txwrapper-orml/src/test-helpers/getRegistryMandala.ts

Now that https://github.com/paritytech/txwrapper-core/pull/170 is in, we can add the options to remove the warnings in our tests for the `txwrapper-orml` package.

fix(tests):  warning generated by orml package tests

---

packages/txwrapper-orml/.npmignore
packages/txwrapper-orml/package.json

Follow up to this https://github.com/paritytech/txwrapper-core/pull/169. 
Sets `.npmignore` the source of truth for bundling our txwrapper-orml package.

fix: txwrapper-orml bundle

---

yarn.lock

This updates shelljs from 0.8.4 -> 0.8.5. 
shelljs is inherited via lerna.

fix: update shelljs according to security advisory

---

packages/txwrapper-core/src/core/util/deriveAddress.spec.ts
packages/txwrapper-core/src/core/util/importPrivateKey.spec.ts
packages/txwrapper-core/src/core/util/index.ts
packages/txwrapper-core/src/core/util/polkadotSS58Format.ts
packages/txwrapper-core/src/test-helpers/constants.ts

This will fix the release, as I removed test-helper directories from the bundled release package, there was one enum that slipped through that is used in the txwrapper-polkadot package, and some of our tests in core.. I changed it to be in the `util` directory so that txwrapper-polkadot can have access to it. 
This is causing the release to fail, and 1.5.1 will need to be published right after.

fix(bug): remove enum from test-helpers, and into util

---

packages/txwrapper-examples/src/polkadot.ts
packages/txwrapper-examples/src/polkadotBatchAll.ts
packages/txwrapper-examples/src/util.ts
packages/txwrapper-template/examples/template-example.ts
packages/txwrapper-template/examples/util.ts

When I first tried to run the examples, `txwrapper` could not connect to my local running node and I was getting the following error :
```
FetchError: request to http://localhost:9933/ failed, reason: connect ECONNREFUSED ::1:9933 at ClientRequest <anonymous>
```
As soon as I replaced in this [line](https://github.com/paritytech/txwrapper-core/blob/d590b0912ee0bf9f357233024c064138cff36cd2/packages/txwrapper-examples/src/util.ts#L23) of code, the `localhost` with `127.0.0.1` or `0.0.0.0`, the connection was established successfully and I could also run the examples.
I suspect that the error appears due to some kind of local settings I have (in vscode or node-js or lack of some dns settings) so it is not an actual error in the code. However, I thought it would be a good practice to still …

fix(examples): replaced localhost with 0.0.0.0

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-core/src/core/method/toTxMethod.ts
packages/txwrapper-examples/package.json
packages/txwrapper-registry/package.json
yarn.lock

"@polkadot/api": "^7.7.1",
"@polkadot/apps-config": "^0.105.1",
"@polkadot/networks": "^8.3.3",
I also added an extra step of validation for the `jsonArg` inside of `toTxMethod` which was failing to serialize the number to string in some cases. I dont think this is a be all end all solution, as toTxMethod needs a little rework, and I dont want to cloud this PR with that logic. I mention it in this issue https://github.com/paritytech/txwrapper-core/issues/126

fix: update polkadot-js deps

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
yarn.lock

"@polkadot/api": "^7.9.1",
"@polkadot/types": "7.9.1",
"@polkadot/types-known": "7.9.1"

fix(deps): Update polkadot deps

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
packages/txwrapper-registry/package.json
yarn.lock

"@polkadot/api": "^7.10.1",
"@polkadot/types": "7.10.1",
"@polkadot/types-known": "7.10.1"

Update polkadot deps

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
packages/txwrapper-registry/package.json
yarn.lock

"@polkadot/api": "^7.11.1",
"@polkadot/types": "7.11.1",
"@polkadot/types-known": "7.11.1",
"@polkadot/apps-config": "^0.108.1"

update api, types, types-known and apps-config

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
packages/txwrapper-registry/package.json
yarn.lock

"@polkadot/api": "^7.12.1",
"@polkadot/keyring": "8.5.1",
"@polkadot/networks": "^8.5.1",
"@polkadot/types": "7.12.1",
"@polkadot/types-known": "7.12.1",
"@polkadot/util": "8.5.1",
"@polkadot/util-crypto": "8.5.1",
"@polkadot/wasm-crypto": "4.6.1",
"@polkadot/apps-config": "^0.109.1"

Update polkadot deps 14 march 2022

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
packages/txwrapper-registry/package.json
yarn.lock

"@polkadot/api": "7.13.1",
"@polkadot/keyring": "8.6.1",
"@polkadot/networks": "8.6.1",
"@polkadot/types": "7.13.1",
"@polkadot/types-known": "7.13.1",
"@polkadot/util": "8.6.1",
"@polkadot/util-crypto": "8.6.1",
"@polkadot/wasm-crypto": "5.0.1",
"@polkadot/apps-config": "0.110.1"

Update polkadot deps 23 march 2022

---

packages/txwrapper-core/src/core/method/defineMethod.spec.ts
packages/txwrapper-core/src/core/method/defineMethod.ts

This resolves a bug where if `info.eraPeriod` is equal to zero it would use the defaults eraPeriod of 64 because it would assume it's a falsey value.

fix(bug): handling eraPeriod when it is equal to zero

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
packages/txwrapper-registry/package.json
yarn.lock

Updates the following deps resolutions, and any that are directly used: 
"@polkadot/api": "7.14.3",
"@polkadot/keyring": "8.7.1",
"@polkadot/networks": "8.7.1",
"@polkadot/types": "7.14.3",
"@polkadot/types-known": "7.14.3",
"@polkadot/util": "8.7.1",
"@polkadot/util-crypto": "8.7.1",
"@polkadot/wasm-crypto": "5.1.1",

fix(deps): update polkadot-js deps

---

packages/txwrapper-substrate/src/methods/balances/transferAll.spec.ts
packages/txwrapper-substrate/src/methods/balances/transferAll.ts
packages/txwrapper-substrate/src/test-helpers/TEST_METHOD_ARGS.ts

closes: [#197](https://github.com/paritytech/txwrapper-core/issues/197)
This adds `transferAll` method to the balances methods in `txwrapper-substrate`. 
Ideally this PR will be followed up by a PR to update the docs.

feat: add balances::transferAll

---

packages/txwrapper-core/src/core/decode/decodeUnsignedTx.spec.ts
packages/txwrapper-core/src/core/decode/decodeUnsignedTx.ts
packages/txwrapper-core/src/core/method/defineMethod.spec.ts
packages/txwrapper-core/src/core/method/defineMethod.ts
packages/txwrapper-core/src/types/method.ts

`defineMethod` will now throw an error when the eraPeriod is less than 4 or greater than 65536. The default value will be 64 if none is passed in. The only way to bypass this is if you are creating an immortal tx.
`isImmortalEra` -> The interface type `options` is now given a key `isImmortalEra` which will allow the user to create an unsigned tx with an immortal era. The default value of this option will always be `undefined` ie. `false`. 
The decoded value of an immortal era will default to '0x00' or `0` via https://github.com/polkadot-js/api/blob/master/packages/types/src/extrinsic/constants.ts#L12.
This will be useful mainly in two places:
`decode` -> for unsigned transactions only.
`defineMethod` -> which residually means all methods used to create unsigned transactions. 
This PR, …

feat!: add `isImmortalEra` option for decoding and encoding era periods

---

CHANGELOG.md
README.md

This updates the readme with a note about verifying versions, and the changelog to reflect version 2.0.0 correctly.

fix(readme-changelog): update correct 2.0.0 release notes, and instructions in the readme

---

.github/workflows/pr.yml
package.json

While running the tests with the command `yarn run test` I got this message at the end : 
```
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
```
So I added the suggested `--detectOpenHandles` option to the jest's related scripts in `package.json` file. I then run the tests again and the message is no longer appearing.

fix: add detectOpenHandles flag in tests (jest)

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
packages/txwrapper-orml/package.json
packages/txwrapper-orml/src/test-helpers/getRegistryMandala.ts
packages/txwrapper-registry/package.json
yarn.lock

Updates the following: 
// Deps
"@polkadot/api": "^10.2.1",
"@polkadot/keyring": "^11.1.2",
// Dev deps
"@polkadot/util-crypto": "^11.1.2",
"@types/node-fetch": "^2.6.2",
Removes the following:
"@acala-network/type-definitions": "^0.7.4-1",

chore(deps): update polkadot-js and remove unnecessary dep bloat

---

README.md
packages/txwrapper-core/README.md
packages/txwrapper-core/src/core/metadata/createMetadata.ts
packages/txwrapper-core/src/core/metadata/getRegistryBase.ts

**Summary**: 
`createMetadata` memoizes the call to ensure metadata is not reallocated in memory if it is the same call.
Methods that actively use `createMetadata` and are affected are:
- `defineMethod`
- `createDecoratedTx`
- `createDecoratedConstants`
- `createSignedTx`
- `decodeSignedTx`
- `decodeSigningPayload`
- `decodeUnsignedTx`
NOTE: `getRegistryBase` uses `createMetadataUnmemoized`
**Summary**: 
Set the max amount of memoized calls we want in the cache. It uses an LRU cache to handle the input and output of values. This takes in an integer. Ex: `export TXWRAPPER_METADATA_CACHE_MAX=10`. This will default to unlimited size if the value is not inputted.
NOTES: 
- It is recommended to use a value greater 2 for the cache size as regressions have been seen in some cases for 2 or lower. …

fix: adjust memoization and cache

---

packages/txwrapper-core/src/core/metadata/createMetadata.ts
packages/txwrapper-core/src/core/util/index.ts
packages/txwrapper-core/src/core/util/isBrowser.ts
packages/txwrapper-registry/src/index.ts

We use `@substrate/txwrapper-core` for some tx operations in the Talisman wallet.
As of https://github.com/paritytech/txwrapper-core/pull/298, this package now throws `Uncaught ReferenceError: process is not defined` because `process.env` is injected by node, but not by browsers.
Since the environment variables used by this package are all optional, I figured a neat solution might be to just safeguard the process.env access.

fix: safer process.env access

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-examples/package.json
packages/txwrapper-registry/package.json
yarn.lock

Updates the following deps:
"@polkadot/util-crypto": "^12.2.1",
"@polkadot/api": "^10.7.1",
"@polkadot/keyring": "^12.2.1",
"@polkadot/networks": "^12.2.1",

chore(deps): update polkadot-js

---

packages/txwrapper-examples/polkadot/README.md

docs: specified in the `README` which rpc-port was used for the polkadot example to avoid `ECONNREFUSED` error.

Specified rpc port for node in polkadot example

---

packages/txwrapper-dev/src/registries/westendRegistry.ts

This change is based on my understanding on the information outlined in the following resource: https://wiki.polkadot.network/docs/learn-DOT#getting-tokens-on-the-westend-testnet.

fix(txwrapper-dev): fix `tokenDecimals` & `ss58Format` values of westend registry

---

packages/txwrapper-core/README.md

closes: https://github.com/paritytech/txwrapper-core/issues/308

docs: fix Metadata cache args

---

packages/txwrapper-substrate/src/methods/balances/index.ts
packages/txwrapper-substrate/src/methods/balances/transferAllowDeath.ts

Export function transferAllowDeath, to be able to use it as `methods.balances.transferAllowDeath`.

fix(txwrapper-substrate): export balances.transferAllowDeath

---

packages/txwrapper-dev/src/constants/constants.ts

I propose this change because I intend to utilize the `getRegistryWestend` function outside this repository. I prefer to rely solely on data from the package, rather than creating a separate constant in my project.

feat(txwrapper-dev): export `WESTEND_SPEC_VERSION` constant

---

packages/txwrapper-polkadot/src/methods/xcmPallet/index.ts
packages/txwrapper-polkadot/src/methods/xcmPallet/limitedReserveTransferAssets.spec.ts
packages/txwrapper-polkadot/src/methods/xcmPallet/limitedReserveTransferAssets.ts
packages/txwrapper-polkadot/src/methods/xcmPallet/limitedTeleportAssets.spec.ts
packages/txwrapper-polkadot/src/methods/xcmPallet/limitedTeleportAssets.ts
packages/txwrapper-polkadot/src/methods/xcmPallet/types.ts

This adds the two following calls: 
```
limitedTeleportAssets
limitedReserveTransferAssets
```

feat(txwrapper-polkadot): Add limited xcm calls for reserve and teleport

---

package.json
yarn.lock

This included, besides the `typedoc` upgrade, the upgrades of `typedoc-plugin-markdown` to `v3.17.1` and `typedoc-plugin-missing-exports` to `v2.2.0`.

fix(deps): bumped `typedoc` to `v0.25.9` 

---

packages/txwrapper-core/src/core/metadata/createMetadata.ts

In Chromium extensions under Manifest Version 3, the project throws an error:
This is because in service workers, `window` is not defined, so `isBrowser` is false, but `process` is also not defined by default.
This could not be fixed by webpack's `DefinePlugin` because of the optional chaining; the optionally-chained expression actually gets transpiled to something quite different in the built package - `typeof process?.env?.TXWRAPPER_METADATA_CACHE_MAX !== 'undefined'` becomes `typeof ((_a = process === null || process === void 0 ? void 0 : process.env) === null || _a === void 0 ? void 0 : _a.TXWRAPPER_METADATA_CACHE_MAX) !== 'undefined'`, which `DefinePlugin` can't parse.
Currently in Talisman as we transition to MV3 we're dealing with this by monkey patching a `process` global variable …

fix: prevent error in service worker environment

---

packages/txwrapper-core/src/core/decode/decodeUnsignedTx.ts
packages/txwrapper-core/src/core/method/defineMethod.ts

As reported on #393, when not specifying the `assetId` to pay for fees, the value defaulted to something other than `undefined` as it's supposed to.
Changed the `assetId` setting in `decodeUnsignedTx.ts` and `defineMethod.ts` in order to catch when the `assetId` is undefined and set it as so.
Previous:
```
assetId: typeof assetId === 'object'
? registry.createType('MultiLocation', assetId)
: registry.createType('Compact<AssetId>', assetId).toNumber()
```
Current:
```
assetId: !assetId ? undefined
: typeof assetId === 'object'
? registry.createType('MultiLocation', assetId)
: registry.createType('Compact<AssetId>', assetId).toNumber()
``` 
Closes #393

fix: set assetId to default to undefined instead of 0

---

package.json
packages/txwrapper-core/package.json
packages/txwrapper-core/src/core/construct/createSignedTx.spec.ts
packages/txwrapper-core/src/core/construct/createSigningPayload.ts
packages/txwrapper-core/src/core/construct/createSigningPayloadToU8a.ts
packages/txwrapper-core/src/core/construct/getTxHash.spec.ts
packages/txwrapper-core/src/core/decode/decodeSignedTx.spec.ts
packages/txwrapper-core/src/core/decode/decodeSigningPayload.ts
packages/txwrapper-core/src/core/decode/decodeUnsignedTx.ts
packages/txwrapper-core/src/core/method/defineMethod.ts
packages/txwrapper-core/src/types/method.ts
packages/txwrapper-dev/package.json
packages/txwrapper-dev/src/util/signWithAliceAstar.ts
packages/txwrapper-examples/assetHubKusama/src/assetHubKusama.ts
packages/txwrapper-examples/assetHubPolkadot/src/assetHubPolkadot.ts
packages/txwrapper-examples/common/util.ts
packages/txwrapper-examples/foreignAssets/src/foreignAssets.ts
packages/txwrapper-examples/multisig/src/multisig.ts
packages/txwrapper-examples/package.json
packages/txwrapper-examples/polkadot/src/polkadot.ts
packages/txwrapper-examples/polkadotBatchAll/src/polkadotBatchAll.ts
packages/txwrapper-registry/package.json
packages/txwrapper-template/examples/template-example.ts
packages/txwrapper-template/examples/util.ts
yarn.lock

Updating PJS/API to 13.1.1 brought changes with the type of the `assetId` used in the `SignerPayloadJSON`: now it's no longer a `number` or an `object` but a `HexString`. In order to conform to this, we changed the way the payload is buitl, first creating the correct type for the assetId (`Compact<u32>` or `Multilocation`) and then converting it to a hex string.

chore(deps): Update PJS

---

package.json
yarn.lock

Downgrading Lerna to last working version. With v8.1.8 all lerna commands don't work locally. Lerna hangs on `lerna notice cli 8.1.8`. Issue reported on the lerna repo [here](https://github.com/lerna/lerna/issues/4064) and [here](https://github.com/lerna/lerna/issues/4063).
Reverts #398

chore(deps): downgrade lerna to v8.1.2

---

.github/dependabot.yml

- Enables the Dependabot to update the packages that match the `@polkadot/*` pattern (same as in [ata](https://github.com/paritytech/asset-transfer-api/pull/457/files))
- Update again the pattern for the Dependabot PR title (same as in [ata](https://github.com/paritytech/asset-transfer-api/pull/464/files))

chore: dependabot config update

---

package.json
yarn.lock

- Removed `rimraf` package. Related to this [comment](https://github.com/paritytech/txwrapper-core/pull/415#issuecomment-2447037250).
- Upgraded `substrate/dev` package to latest version.
- `yarn remove rimraf`
- `yarn`
- `yarn dedupe`
- `yarn build`
- `yarn test`
I did not encounter any errors at any step.

chore(deps-dev): remove rimraf & update substrate/dev to latest version
