- package.json
- packages/txwrapper-core/package.json
- packages/txwrapper-core/src/types/codec.ts
- packages/txwrapper-examples/package.json
- packages/txwrapper-orml/src/test-helpers/getRegistryMandala.ts
- packages/txwrapper-registry/package.json
- packages/txwrapper-registry/src/index.ts
- packages/txwrapper-template/package.json
- yarn.lock
Closes #53 
Aligns with `ChainProperties` in polkadot-js as defined here: 
https://github.com/polkadot-js/api/blob/9269d94677112fa80013cf55575421fea26cbfc0/packages/types/src/generic/ChainProperties.ts#L59-L84
> fix: Align ChainProperties with polkadot-js def

- packages/txwrapper-substrate/src/methods/staking/bond.ts
- packages/txwrapper-substrate/src/methods/staking/setPayee.ts
rel: https://github.com/paritytech/txwrapper/pull/393
> fix: Update `RewardDestination` argument type for `staking.setPayee`

- packages/txwrapper-substrate/src/methods/proxy/anonymous.spec.ts
- packages/txwrapper-substrate/src/methods/proxy/anonymous.ts
- packages/txwrapper-substrate/src/methods/proxy/index.ts
- packages/txwrapper-substrate/src/test-helpers/TEST_METHOD_ARGS.ts
This pr adds the `proxy.anonymous` pallet method to the txwrapper-substrate package.
closes #79
> feat(txwrapper-substrate): Add proxy.anonymous

- CHANGELOG.md
- lerna.json
- packages/txwrapper-acala/CHANGELOG.md
- packages/txwrapper-acala/package.json
- packages/txwrapper-core/CHANGELOG.md
- packages/txwrapper-core/package.json
- packages/txwrapper-examples/CHANGELOG.md
- packages/txwrapper-examples/package.json
- packages/txwrapper-orml/CHANGELOG.md
- packages/txwrapper-orml/package.json
- packages/txwrapper-polkadot/CHANGELOG.md
- packages/txwrapper-polkadot/package.json
- packages/txwrapper-registry/CHANGELOG.md
- packages/txwrapper-registry/package.json
- packages/txwrapper-substrate/CHANGELOG.md
- packages/txwrapper-substrate/package.json
- packages/txwrapper-template/CHANGELOG.md
- packages/txwrapper-template/package.json
> chore(release): publish

- README.md
> docs: Update release notes

- README.md
Update the release notes with a yubikey caveat warning.
> docs: yubikey warning

- README.md
- packages/txwrapper-core/package.json
- packages/txwrapper-examples/package.json
- packages/txwrapper-registry/package.json
- yarn.lock
- Polkadot deps
- Release section of README
> fix(types): Update polkadot-js deps to get the latest types

- packages/txwrapper-examples/README.md
- yarn.lock
closes: [#122](https://github.com/paritytech/txwrapper-core/issues/122)
Fixes the README in txwrapper-examples for launching the example.
> docs: update txwrapper-examples readme

- packages/txwrapper-registry/package.json
- yarn.lock
rel: [#130](https://github.com/paritytech/txwrapper-core/issues/130)
Updates apps-config to ensure no downstream dep error with lodash. 
Since I am OOO, please feel free to merge once approved.
> fix: apps-config version for lodash downstream

- CHANGELOG.md
This reverts commit a35965837421b9a42094559c736159b0dbc7c521.
I messed up the release process with #135, it should be done with lerna let's hope this works.
> Revert "chore(release): publish (#135)"

- package.json
- packages/txwrapper-core/package.json
- packages/txwrapper-examples/package.json
- packages/txwrapper-registry/package.json
- yarn.lock
This PR bumps the deps for:
`@polkadot/api`
`@polkadot/apps-config` -> contains a fix involving darwinian types.
> fix(deps): bump deps, important(apps-config)

- yarn.lock
Update yarn.lock to align with the deps in all the packages. Fixes the CI
> fix(deps): update lock

- package.json
- packages/txwrapper-core/package.json
- packages/txwrapper-examples/package.json
- packages/txwrapper-registry/package.json
- yarn.lock
Update the deps, and resolutions.
> fix(deps): bump polkadot-js, cleanup resolutions

- package.json
- packages/txwrapper-core/package.json
- packages/txwrapper-examples/package.json
- packages/txwrapper-registry/package.json
- yarn.lock
Bumps:
"@polkadot/api" -> 6.8.1
"@polkadot/apps-config" -> 0.98.2-70
> fix: bump polkadot-js deps

- package.json
- packages/txwrapper-core/package.json
- packages/txwrapper-examples/package.json
- packages/txwrapper-registry/package.json
- yarn.lock
Bump the following deps
"@polkadot/api": "^6.9.2",
"@polkadot/apps-config": "0.98.2-94",
"@polkadot/networks": "^7.9.2",
> fix(types): bump polkadot deps

- package.json
- packages/txwrapper-core/package.json
- packages/txwrapper-examples/package.json
- packages/txwrapper-registry/package.json
- yarn.lock
Update polkadot-js deps
"@polkadot/api": "^6.11.1"
"@polkadot/networks": "^8.1.2"
> fix(deps): bump polkadot-js deps

- packages/txwrapper-substrate/src/methods/balances/index.ts
rel: [#200](https://github.com/paritytech/txwrapper-core/pull/200)
patch for exporting transferAll.
> fix: export for transferAll

- README.md
- package.json
- yarn.lock
Update substrate-js-dev to `0.6.0` and adds the script `yarn update-pjs-deps` which will update all the resolutions and packages to the latest version.
> fix: update substrate-js-dev, add update-pjs-script

- package.json
- packages/txwrapper-core/package.json
- packages/txwrapper-examples/package.json
- packages/txwrapper-registry/package.json
- yarn.lock
Update the following deps:
"@polkadot/api": "^9.11.1",
"@polkadot/keyring": "^10.2.3",
"@polkadot/util-crypto": "^10.2.3",
"@polkadot/networks": "^10.2.3",
> chore(deps): udpate polkadot-js api, util-crypto, networks, keyring

- README.md
- package.json
@Imod7 This updates the scripts and readme docs
> chore: remove unneccessary script and update docs

- package.json
- packages/txwrapper-core/package.json
- packages/txwrapper-examples/package.json
- packages/txwrapper-registry/package.json
- yarn.lock
updates the following polkadot-js deps:
"@polkadot/util-crypto": "^10.4.2",
"@polkadot/api": "^9.14.2",
"@polkadot/keyring": "^10.4.2",
"@polkadot/networks": "^10.4.2",
> chore(deps): update pjs

- package.json
- yarn.lock
Updates `@substrate/dev` to 0.6.7
> chore(deps): Update @substrate/dev

- .github/workflows/semantic.yml
Add a PR title check to ensure its semantic, and following conventional commits
> ci: add semantic title check

- packages/txwrapper-examples/foreignAssets/README.md
- packages/txwrapper-examples/foreignAssets/src/foreignAssets.ts
- packages/txwrapper-examples/package.json
- packages/txwrapper-examples/tsconfig.build.json
- zombienet/config/asset-hub.toml
Following #362 , now an example on how to transfer foreign assets was added.
> chore(examples): Added example for foreign asset

- packages/txwrapper-core/package.json
- packages/txwrapper-dev/package.json
- packages/txwrapper-examples/package.json
- yarn.lock
This updates `polkadot/api` to v14.0.1
> chore(deps): update PJS deps

- .github/dependabot.yml
Tiny correction on the indendation
> fix: dependabot indendation

- package.json
- packages/txwrapper-examples/assetHubKusama/src/assetHubKusama.ts
- packages/txwrapper-examples/assetHubPolkadot/src/assetHubPolkadot.ts
- packages/txwrapper-examples/foreignAssets/src/foreignAssets.ts
- packages/txwrapper-examples/multisig/src/multisig.ts
- packages/txwrapper-examples/polkadot/src/polkadot.ts
- packages/txwrapper-template/examples/template-example.ts
- yarn.lock
Replaces #453 in order to fix CI errors.
> chore(deps-dev): bumped tslint version
